name: Convert PowerShell Script to EXE

on:
  push:
    branches:
      - main  # oder dein spezifischer Branch
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install PSScriptAnalyzer
      shell: pwsh
      run: |
        Install-Module -Name PSScriptAnalyzer -Force -Scope CurrentUser

    - name: Install PS2EXE
      run: Install-Module -Name PS2EXE -Force -Scope CurrentUser

    - name: Convert PS1 to EXE
      run: |
        New-PS2EXE -inputFile ./Repair-Windows.ps1 -outputFile ./Repair-Windows.exe

    - name: Upload EXE as Artifact
      uses: actions/upload-artifact@v3
      with:
        name: Repair-Windows
        path: ./LOONY-TECH - Windows Repair.exe
